## Data Manipulation with Pandas

Data manipulation refers to the process of cleaning, transforming, and modifying data to make it suitable for analysis. In Pandas, this is achieved using powerful DataFrame and Series operations.

Common data manipulation tasks include:
- Adding, removing, or renaming columns and rows  
- Handling missing values (null or NaN data)  
- Filtering and selecting subsets of data  
- Sorting and indexing data efficiently  
- Performing aggregations and transformations  

Pandas provides functions such as `drop()`, `rename()`, `fillna()`, `astype()`, and boolean indexing, which allow efficient and readable data manipulation. These operations help prepare raw datasets into a structured and analysis-ready format.

In [58]:
import pandas as pd
import numpy as np

In [59]:
df = pd.read_csv('Online_Sales_Data.csv')
df.head() # first five rows

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [60]:
df.tail() # last five rows

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [31]:
# Describe the DataFrame
print("Statistical summary: \n", df.describe())

Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [32]:
# Display the data types of each column
print("Data types: \n", df.dtypes)

Data types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object

In [33]:
# handling missing values

df.isnull().any()

Transaction ID      False
Date                False
Product Category    False
Product Name        False
Units Sold          False
Unit Price          False
Total Revenue       False
Region              False
Payment Method      False
dtype: bool

In [34]:
df.isnull().sum()

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

In [35]:
# no missing values in dataset

# df_filled = df.fillna(0) # fill missing values with 0


# filling missing vales wih mean
# df['Sales_filled'] = df['Sales'].fillna(df['Sales'].mean())

In [36]:
# rename columns
df.rename(columns={'Transaction ID':'transaction_ID', 'Date':'sales_date', 'Product Category':'product_category','Product Name':'product_name', 'Units Sold':'units_sold', 'Unit Price':'unit_price', 'Total Revenue': 'total_revenue', 'Region':'region', 'Payment Method':'payment_method'}, inplace=True)
df.head()

,transaction_ID,sales_date,product_category,product_name,units_sold,unit_price,total_revenue,region,payment_method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
# change datatypes
df['new_revenue'] = df['total_revenue'].astype(int)
df.head()

# if there was missing value while changing datatype then fill it
# df['new_revenue'] = df['total_revenue'].fillna(df['total_revenue'].mean()).astype(int)

,transaction_ID,sales_date,product_category,product_name,units_sold,unit_price,total_revenue,region,payment_method,new_revenue
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89

In [39]:
df['doubled_unit_price'] = df['unit_price'].apply(lambda x:x*2)
df.head()

,transaction_ID,sales_date,product_category,product_name,units_sold,unit_price,total_revenue,region,payment_method,new_revenue,doubled_unit_price
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999,1999.98
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499,999.98
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209,139.98
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63,31.98
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89,179.98

In [42]:
# Data Agggregating and Grouping
grouped_mean = df.groupby('product_category')['total_revenue'].mean()
print(grouped_mean)

product_category
Beauty Products     65.54750
Books               46.54825
Clothing           203.22325
Electronics        874.56025
Home Appliances    466.15400
Sports             358.16300
Name: total_revenue, dtype: float64

In [44]:
grouped_sum = df.groupby(['product_category', 'region'])['total_revenue'].sum()
print(grouped_sum)

product_category  region
Beauty Products   Europe            2621.90
Books             North America     1861.93
Clothing          Asia              8128.93
Electronics       North America    34982.41
Home Appliances   Europe           18646.16
Sports            Asia             14326.52
Name: total_revenue, dtype: float64

In [47]:
# aggregate multiple functions
grouped_agg = df.groupby('region')['unit_price'].agg(['mean', 'sum', 'count'])
grouped_agg

                    mean       sum  count
region
Asia           164.41025  13152.82     80
Europe         190.90425  15272.34     80
North America  353.87225  28309.78     80

In [51]:
# merging and joining dataframes

df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1,2,3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4,5,6]})

In [52]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [53]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [ ]:
# merge DatFrame on the 'Key' columns
pd.merge(df1, df2, on='Key', how='inner') # inner join

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [55]:
pd.merge(df1, df2, on='Key', how='outer') # outer join

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [56]:
pd.merge(df1, df2, on='Key', how='left') # left join

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [57]:
pd.merge(df1, df2, on='Key', how='right') # right join

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6