### Pandas-DataFrame and Series

Pandas is a powerful data manipulation library in python widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd
data=[1,2,3,4,5]
series = pd.Series(data)
print("Series\n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [2]:
# create a series from dictionary
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [3]:
data = [10, 20, 30]
index = ['a', 'b', 'c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [4]:
# DataFrame

# create a dataframe from a dictionary of list
data = {
    'Name':['Tejas', 'Tom', 'Jerry'],
    'Age': [20, 80, 60],
    'City':['Bangalore', 'New York', 'Florida']
}
df1 = pd.DataFrame(data)
print(df1)
print(type(df1))

    Name  Age       City
0  Tejas   20  Bangalore
1    Tom   80   New York
2  Jerry   60    Florida
<class 'pandas.DataFrame'>

In [5]:
import numpy as np
np.array(df1)

array([['Tejas', 20, 'Bangalore'],
       ['Tom', 80, 'New York'],
       ['Jerry', 60, 'Florida']], dtype=object)

In [6]:
# create a dataframe from a list of dictionary

data = [
    { 'Name': 'Tejas', 'Age': 20, 'City':'Bangalore'},
    { 'Name': 'John', 'Age': 29, 'City':'Vellore'},
    { 'Name': 'Adam', 'Age': 22, 'City':'Mangaluru'}
]

df2 = pd.DataFrame(data)
print(df2)
print(type(df2))

    Name  Age       City
0  Tejas   20  Bangalore
1   John   29    Vellore
2   Adam   22  Mangaluru
<class 'pandas.DataFrame'>

In [10]:
# Accessing data from DataFrame
df2

    Name  Age       City
0  Tejas   20  Bangalore
1   John   29    Vellore
2   Adam   22  Mangaluru

In [ ]:
df2['Name']

0    Tejas
1     John
2     Adam
Name: Name, dtype: str

In [13]:
df2.loc[0] # access 1st row

Name        Tejas
Age            20
City    Bangalore
Name: 0, dtype: object

In [18]:
# Accessing a specified element
df2.at[1, 'Age']

np.int64(29)

In [19]:
# accessing a specified element using iat
df2.iat[2, 2]

'Mangaluru'

In [20]:
# Data Manipulation with DataFrame
df2

    Name  Age       City
0  Tejas   20  Bangalore
1   John   29    Vellore
2   Adam   22  Mangaluru

In [21]:
# add new column
df2['Salary'] = [50000, 60000, 40000]
df2

    Name  Age       City  Salary
0  Tejas   20  Bangalore   50000
1   John   29    Vellore   60000
2   Adam   22  Mangaluru   40000

In [23]:
# Remove the 'Salary' column
# axis=1 specifies column-wise operation (axis=0 is row-wise by default)
df2.drop('Salary', axis=1, inplace=True)
df2

    Name  Age       City
0  Tejas   20  Bangalore
1   John   29    Vellore
2   Adam   22  Mangaluru

In [24]:
# Add +1 year to the age column
df2['Age'] = df2['Age'] + 1
df2

    Name  Age       City
0  Tejas   21  Bangalore
1   John   30    Vellore
2   Adam   23  Mangaluru